manifest:
  version: 0.13

  projects:
    - name: nrf
      revision: v2.9.0
      path: deps
      url: http://github.com/nrfconnect/sdk-nrf
      import:
        name-allowlist:
          - zephyr

  self:
    path: app
